const allProductsData = [
    {
        id: 0,
        bottle: 'niegazowane_pomarancza',
        name: 'jabłko - pomarańcza',
        tableLabels: {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },
        tableValues: {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '163 kJ / 38 kcal',
                tluszcz: '0g',
                wTymKwasyNasycone: '0g',
                weglowodany: '9.6g',
                wTymCukry: '8.7g',
                bialko: '0g',
                sol: '0g',
        },
        category: 'non_carb_drink',
        price: 1.67,
        netPrice: 1.67,
        vat: 0,
        hint: '[NIEGAZ]',
    },
    {
        id: 1,
        bottle: 'niegazowane_lesne',
        name: 'owoce leśne',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },
        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '165 kJ / 39 kcal',
                tluszcz: '0.1g',
                wTymKwasyNasycone: '<0.1g',
                weglowodany: '9.5g',
                wTymCukry: '9.4g',
                bialko: '<0.5g',
                sol: '<0.05g',
            },
        category: 'non_carb_drink',
        price: 1.67,
        netPrice: 1.67,
        vat: 0,
        hint: '[NIEGAZ]',
    },
    {
        id: 2,
        bottle: 'niegazowane_porzeczka',
        name: 'jabłko - porzeczka',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },
        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '179 kJ / 42 kcal',
                tluszcz: '0g',
                wTymKwasyNasycone: '0g',
                weglowodany: '11g',
                wTymCukry: '8.9g',
                bialko: '0g',
                sol: '0g',
            },
        category: 'non_carb_drink',
        price: 1.67,
        netPrice: 1.67,
        vat: 0,
        hint: '[NIEGAZ]',
    },
    {
        id: 3,
        bottle: 'niegazowane_wisnia',
        name: 'jabłko - wiśnia',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },
        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '177 kJ / 42 kcal',
                tluszcz: '0g',
                wTymKwasyNasycone: '0g',
                weglowodany: '10g',
                wTymCukry: '10g',
                bialko: '0g',
                sol: '<0.05g',
            },
        category: 'non_carb_drink',
        price: 1.67,
        netPrice: 1.67,
        vat: 0,
        hint: '[NIEGAZ]',
    },
    {
        id: 4,
        bottle: 'niegazowane_brzoskwinia',
        name: 'jabłko - brzoskwinia',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },
        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '163 kJ / 38 kcal',
                tluszcz: '0g',
                wTymKwasyNasycone: '0g',
                weglowodany: '9.6g',
                wTymCukry: '9.2g',
                bialko: '0g',
                sol: '0g',
            },
        category: 'non_carb_drink',
        price: 1.67,
        netPrice: 1.67,
        vat: 0,
        hint: '[NIEGAZ]',
    },
    {
        id: 5,
        bottle: 'niegazowane_winogronowy',
        name: 'winogrono - jabłko',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },
        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '168 kJ / 40 kcal',
                tluszcz: '0g',
                wTymKwasyNasycone: '0g',
                weglowodany: '9.9g',
                wTymCukry: '9.3g',
                bialko: '0g',
                sol: '0g',
            },
        category: 'non_carb_drink',
        price: 1.67,
        netPrice: 1.67,
        vat: 0,
        hint: '[NIEGAZ]',
    },
    {
        id: 6,
        bottle: 'niegazowane_jablko',
        name: 'jabłko',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },
        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '162 kJ / 38 kcal',
                tluszcz: '0g',
                wTymKwasyNasycone: '0g',
                weglowodany: '9.3g',
                wTymCukry: '9.2g',
                bialko: '0g',
                sol: '<0.05g',
            },

        category: 'non_carb_drink',
        price: 1.67,
        netPrice: 1.67,
        vat: 0,
        hint: '[NIEGAZ]',
    },
    {
        id: 7,
        bottle: 'niegazowane_gruszka',
        name: 'jabłko - gruszka',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },

        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '161 kJ / 38 kcal',
                tluszcz: '0g',
                wTymKwasyNasycone: '0g',
                weglowodany: '9g',
                wTymCukry: '8.8g',
                bialko: '0g',
                sol: '<0.05g',
            },

        category: 'non_carb_drink',
        price: 1.67,
        netPrice: 1.67,
        vat: 0,
        hint: '[NIEGAZ]',
    },
    {
        id: 8,
        bottle: 'niegazowane_mieta',
        name: 'jabłko - mięta',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },

        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '165 kJ / 39 kcal',
                tluszcz: '0g',
                wTymKwasyNasycone: '0g',
                weglowodany: '9.5g',
                wTymCukry: '9.4g',
                bialko: '0g',
                sol: '<0.05g',
            },

        category: 'non_carb_drink',
        price: 1.67,
        netPrice: 1.67,
        vat: 0,
        hint: '[NIEGAZ]',
    },
    {
        id: 9,
        bottle: 'niegazowane_owocowy',
        name: 'wieloowocowy',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },

        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '161 kJ / 38 kcal',
                tluszcz: '0g',
                wTymKwasyNasycone: '0g',
                weglowodany: '9.2g',
                wTymCukry: '8.9g',
                bialko: '0g',
                sol: '<0.05g',
            },

        category: 'non_carb_drink',
        price: 1.67,
        netPrice: 1.67,
        vat: 0,
        hint: '[NIEGAZ]',
    },
    {
        id: 10,
        bottle: 'gazowane_tonic',
        name: 'tonic',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },

        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '77 kJ / 18 kcal',
                tluszcz: '0g',
                wTymKwasyNasycone: '0g',
                weglowodany: '4.5g',
                wTymCukry: '4g',
                bialko: '0g',
                sol: '0g',
            },

        category: 'carb_drink',
        price: 1.46,
        netPrice: 1.19,
        vat: 23,
        hint: '[GAZ]',
    },
    {
        id: 11,
        bottle: 'gazowane_grejpfrut',
        name: 'grejpfrut',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },

        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '77 kJ / 18 kcal',
                tluszcz: '0g',
                wTymKwasyNasycone: '0g',
                weglowodany: '4.5g',
                wTymCukry: '4g',
                bialko: '0g',
                sol: '0g',
            },

        category: 'carb_drink',
        price: 1.46,
        netPrice: 1.19,
        vat: 23,
        hint: '[GAZ]',
    },
    {
        id: 12,
        bottle: 'gazowane_tropic',
        name: 'owoce egzotyczne',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },

        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '77 kJ / 18 kcal',
                tluszcz: '0g',
                wTymKwasyNasycone: '0g',
                weglowodany: '4.5g',
                wTymCukry: '4g',
                bialko: '0g',
                sol: '0g',
            },

        category: 'carb_drink',
        price: 1.46,
        netPrice: 1.19,
        vat: 23,
        hint: '[GAZ]',
    },
    {
        id: 13,
        bottle: 'gazowane_kiwi',
        name: 'kiwi',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },

        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '77 kJ / 18 kcal',
                tluszcz: '0g',
                wTymKwasyNasycone: '0g',
                weglowodany: '4.5g',
                wTymCukry: '4g',
                bialko: '0g',
                sol: '0g',
            },

        category: 'carb_drink',
        price: 1.46,
        netPrice: 1.19,
        vat: 23,
        hint: '[GAZ]',
    },
    {
        id: 14,
        bottle: 'gazowane_lima',
        name: 'cytryna - limonka',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },

        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '77 kJ / 18 kcal',
                tluszcz: '0g',
                wTymKwasyNasycone: '0g',
                weglowodany: '4.5g',
                wTymCukry: '3.2g',
                bialko: '0g',
                sol: '0g',
            },

        category: 'carb_drink',
        price: 1.46,
        netPrice: 1.19,
        vat: 23,
        hint: '[GAZ]',
    },
    {
        id: 15,
        bottle: 'gazowane_ananas',
        name: 'ananas',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },

        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '77 kJ / 18 kcal',
                tluszcz: '0g',
                wTymKwasyNasycone: '0g',
                weglowodany: '4.5g',
                wTymCukry: '4g',
                bialko: '0g',
                sol: '0g',
            },

        category: 'carb_drink',
        price: 1.46,
        netPrice: 1.19,
        vat: 23,
        hint: '[GAZ]',
    },
    {
        id: 16,
        bottle: 'gazowane_brzoskwinia',
        name: 'brzoskwinia',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },

        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '77 kJ / 18 kcal',
                tluszcz: '0g',
                wTymKwasyNasycone: '0g',
                weglowodany: '4.5g',
                wTymCukry: '4g',
                bialko: '0g',
                sol: '0g',
            },

        category: 'carb_drink',
        price: 1.46,
        netPrice: 1.19,
        vat: 23,
        hint: '[GAZ]',
    },
    {
        id: 17,
        bottle: 'gazowane_orange',
        name: 'pomarańcz',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },

        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '77 kJ / 18 kcal',
                tluszcz: '0g',
                wTymKwasyNasycone: '0g',
                weglowodany: '4.5g',
                wTymCukry: '4g',
                bialko: '0g',
                sol: '0g',
            },

        category: 'carb_drink',
        price: 1.46,
        netPrice: 1.19,
        vat: 23,
        hint: '[GAZ]',
    },
    {
        id: 18,
        bottle: 'gazowane_lemon',
        name: 'cytryna',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },

        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '77 kJ / 18 kcal',
                tluszcz: '0g',
                wTymKwasyNasycone: '0g',
                weglowodany: '4.5g',
                wTymCukry: '4g',
                bialko: '0g',
                sol: '0g',
            },

        category: 'carb_drink',
        price: 1.46,
        netPrice: 1.19,
        vat: 23,
        hint: '[GAZ]',
    },
    {
        id: 19,
        bottle: 'gazowane_cola',
        name: 'cola',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },

        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '68 kJ / 16 kcal',
                tluszcz: '0g',
                wTymKwasyNasycone: '0g',
                weglowodany: '4.5g',
                wTymCukry: '3.6g',
                bialko: '0g',
                sol: '0g',
            },

        category: 'carb_drink',
        price: 1.46,
        netPrice: 1.19,
        vat: 23,
        hint: '[GAZ]',
    },
    {
        id: 20,
        bottle: 'gazowane_czerwona',
        name: 'oranżada czerwona',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },

        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '77 kJ / 18 kcal',
                tluszcz: '0g',
                wTymKwasyNasycone: '0g',
                weglowodany: '4.5g',
                wTymCukry: '4g',
                bialko: '0g',
                sol: '0g',
            },

        category: 'carb_drink',
        price: 1.46,
        netPrice: 1.19,
        vat: 23,
        hint: '[GAZ]',
    },
    {
        id: 21,
        bottle: 'gazowane_biala',
        name: 'oranżada biała',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },

        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '77 kJ / 18 kcal',
                tluszcz: '0g',
                wTymKwasyNasycone: '0g',
                weglowodany: '4.5g',
                wTymCukry: '4g',
                bialko: '0g',
                sol: '0g',
            },

        category: 'carb_drink',
        price: 1.46,
        netPrice: 1.19,
        vat: 23,
        hint: '[GAZ]',
    },
    {
        id: 22,
        bottle: 'soki_grejpfrutowy',
        name: 'grejpfrut',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },

        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '169 kJ / 40 kcal',
                tluszcz: '0g',
                wTymKwasyNasycone: '0g',
                weglowodany: '9.5g',
                wTymCukry: '8.2g',
                bialko: '0.5g',
                sol: '0g',
            },

        category: 'juices',
        price: 2.08,
        netPrice: 2.08,
        vat: 0,
        hint: '[SOK]',
    },
    {
        id: 23,
        bottle: 'soki_jablkowy',
        name: 'jabłko',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },

        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '164 kJ / 39 kcal',
                tluszcz: '0g',
                wTymKwasyNasycone: '0g',
                weglowodany: '11g',
                wTymCukry: '11g',
                bialko: '0.1g',
                sol: '0g',
            },

        category: 'juices',
        price: 2.08,
        netPrice: 2.08,
        vat: 0,
        hint: '[SOK]',
    },
    {
        id: 24,
        bottle: 'soki_pomaranczowy',
        name: 'pomarańcz',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },

        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '193 kJ / 45 kcal',
                tluszcz: '0g',
                wTymKwasyNasycone: '0g',
                weglowodany: '10g',
                wTymCukry: '9.4g',
                bialko: '1.1g',
                sol: '0g',
            },

        category: 'juices',
        price: 2.08,
        netPrice: 2.08,
        vat: 0,
        hint: '[SOK]',
    },
    {
        id: 25,
        bottle: 'soki_porzeczkowy',
        name: 'czarna porzeczka',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },

        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '235 kJ / 55 kcal',
                tluszcz: '0g',
                wTymKwasyNasycone: '0g',
                weglowodany: '14g',
                wTymCukry: '14g',
                bialko: '0.1g',
                sol: '0g',
            },

        category: 'juices',
        price: 2.08,
        netPrice: 2.08,
        vat: 0,
        hint: '[SOK]',
    },
    {
        id: 26,
        bottle: 'soki_pomidorowy',
        name: 'pomidor',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
            },

        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '99 kJ / 23 kcal',
                tluszcz: '0g',
                wTymKwasyNasycone: '0g',
                weglowodany: '5g',
                wTymCukry: '3.3g',
                bialko: '0.8g',
                sol: '0.42g',
            },

        category: 'juices',
        price: 2.08,
        netPrice: 2.08,
        vat: 0,
        hint: '[SOK]',
    },
    {
        id: 27,
        bottle: 'bogus_truskawka',
        name: 'truskawka - jabłko - marchew',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
                witaminaC: 'Witamina C',
            },

        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '205 kJ / 48 kcal',
                tluszcz: '0.1g',
                wTymKwasyNasycone: '0g',
                weglowodany: '12g',
                wTymCukry: '11g',
                bialko: '0.2g',
                sol: '<0.05g',
                witaminaC: '24 mg / 30%',
            },

        category: 'bogus',
        price: 2.08,
        netPrice: 2.08,
        vat: 0,
        hint: '[B]',
    },
    {
        id: 28,
        bottle: 'bogus_brzoskwinia',
        name: 'brzoskwinia - jabłko - marchew',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
                witaminaC: 'Witamina C',
            },

        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '209 kJ / 49 kcal',
                tluszcz: '0.1g',
                wTymKwasyNasycone: '0g',
                weglowodany: '12g',
                wTymCukry: '11g',
                bialko: '0.3g',
                sol: '<0.05g',
                witaminaC: '23 mg / 29%',
            },

        category: 'bogus',
        price: 2.08,
        netPrice: 2.08,
        vat: 0,
        hint: '[B]',
    },
    {
        id: 29,
        bottle: 'bogus_banan',
        name: 'banan - jabłko - marchew',
        tableLabels:
            {
                wartoscOdzywcza: 'Wartość odżywcza',
                wartoscEnergetyczna: 'Wartość energetyczna',
                tluszcz: 'Tłuszcz',
                wTymKwasyNasycone: 'w tym kwasy nasycone',
                weglowodany: 'Węglowodany',
                wTymCukry: 'w tym cukry',
                bialko: 'Białko',
                sol: 'Sól',
                witaminaC: 'Witamina C',
            },

        tableValues:
            {
                wartoscOdzywcza: 'w 100ml produktu',
                wartoscEnergetyczna: '211 kJ / 50 kcal',
                tluszcz: '0.1g',
                wTymKwasyNasycone: '0g',
                weglowodany: '12g',
                wTymCukry: '11g',
                bialko: '0.3g',
                sol: '<0.05g',
                witaminaC: '23 mg / 29%',
            },

        category: 'bogus',
        price: 2.08,
        netPrice: 2.08,
        vat: 0,
        hint: '[B]',
    },
    {
        id: 30,
        bottle: 'woda_niegazowana',
        name: 'źródlana woda niegazowana',
        tableLabels:
            {
                kationy: 'Kationy:',
                wapniowy: '- wapniowy',
                magnezowy: '- magnezowy',
                sodowy: '- sodowy',
                potasowy: '- potasowy',
                aniony: 'Aniony:',
                wodoroweglanowy: '- wodorowęglanowy',
                siarczanowy: '- siarczanowy',
                chlorkowy: '- chlorkowy',
                fluorkowy: '- fluorkowy',
                suma: 'Suma składników mineralnych',
            },

        tableValues:
            {
                kationy: '.',
                wapniowy: '86.33 mg/l',
                magnezowy: '12.52 mg/l',
                sodowy: '31.40 mg/l',
                potasowy: '2.27 mg/l',
                aniony: '.',
                wodoroweglanowy: '323.7 mg/l',
                siarczanowy: '58.68 mg/l',
                chlorkowy: '21.1 mg/l',
                fluorkowy: '0.153 mg/l',
                suma: '559.8 mg/l',
            },

        category: 'water',
        price: 1.0,
        netPrice: 0.81,
        vat: 23,
        hint: '[WODA]',
    },
    {
        id: 31,
        bottle: 'woda_sredniogazowana',
        name: 'źródlana woda średnio gazowana',
        tableLabels:
            {
                kationy: 'Kationy:',
                wapniowy: '- wapniowy',
                magnezowy: '- magnezowy',
                sodowy: '- sodowy',
                potasowy: '- potasowy',
                aniony: 'Aniony:',
                wodoroweglanowy: '- wodorowęglanowy',
                siarczanowy: '- siarczanowy',
                chlorkowy: '- chlorkowy',
                fluorkowy: '- fluorkowy',
                suma: 'Suma składników mineralnych',
            },

        tableValues:
            {
                kationy: '.',
                wapniowy: '86.33 mg/l',
                magnezowy: '12.52 mg/l',
                sodowy: '31.40 mg/l',
                potasowy: '2.27 mg/l',
                aniony: '.',
                wodoroweglanowy: '323.7 mg/l',
                siarczanowy: '58.68 mg/l',
                chlorkowy: '21.1 mg/l',
                fluorkowy: '0.153 mg/l',
                suma: '559.8 mg/l',
            },

        category: 'water',
        price: 1.0,
        netPrice: 0.81,
        vat: 23,
        hint: '[WODA]',
    },
    {
        id: 32,
        bottle: 'woda_gazowana',
        name: 'źródlana woda gazowana',
        tableLabels:
            {
                kationy: 'Kationy:',
                wapniowy: '- wapniowy',
                magnezowy: '- magnezowy',
                sodowy: '- sodowy',
                potasowy: '- potasowy',
                aniony: 'Aniony:',
                wodoroweglanowy: '- wodorowęglanowy',
                siarczanowy: '- siarczanowy',
                chlorkowy: '- chlorkowy',
                fluorkowy: '- fluorkowy',
                suma: 'Suma składników mineralnych',
            },

        tableValues:
            {
                kationy: '.',
                wapniowy: '86.33 mg/l',
                magnezowy: '12.52 mg/l',
                sodowy: '31.40 mg/l',
                potasowy: '2.27 mg/l',
                aniony: '.',
                wodoroweglanowy: '323.7 mg/l',
                siarczanowy: '58.68 mg/l',
                chlorkowy: '21.1 mg/l',
                fluorkowy: '0.153 mg/l',
                suma: '559.8 mg/l',
            },

        category: 'water',
        price: 1.0,
        netPrice: 0.81,
        vat: 23,
        hint: '[WODA]',
    },
];

export default allProductsData;

export function getProductsByCategory(categoryUrl) {
    return allProductsData.filter((bd) => bd.category === categoryUrl);
}
